name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install coverage pylint

      - name: Lint (pylint, no bloqueante)
        continue-on-error: true
        env:
          PYTHONWARNINGS: ignore
        run: |
          # Limitar a los paquetes del proyecto; ignora errores de salida para no bloquear
          pylint core cli pygame_ui main_pygame.py --exit-zero || true

      - name: Run tests with coverage
        env:
          BACKGAMMON_SKIP_MAIN: '1'
        run: |
          coverage run -m unittest

      - name: Coverage report (fail under 95%)
        run: |
          coverage report -m
          coverage xml
          coverage report --fail-under=95

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: error
